Add in-home chime support to CLI
python-ring-doorbell/python-ring-doorbell pull request #427
Opened 2024-09-03 13:30 UTC by briangoldstein

Added a command `in-home-chime` which supports viewing the current in-home chime settings for a device as well as changing any of the available settings using multiple arguments.

Sample output of `ring-doorbell in-home-chime --device-name "Front Door"`

> Name:       Front Door
> ID:         987652
> Type:       Digital
> Enabled:    True
> Duration:   5

Output of `ring-doorbell in-home-chime --help`

> Usage: ring-doorbell in-home-chime [OPTIONS]
> 
>   View and manage the Doorbell in-home chime. To see the current in-home chime
>   status of a device, only pass the device name.
> 
> Options:
>   -dn, --device-name TEXT         Name of the ring device  [required]
>   -t, --type [Mechanical|Digital|Not Present]  Set the in-home chime type.
>   -e, --enabled [True|False]      Enable or disable the in-home chime.
>   -d, --duration [0|1|2|3|4|5|6|7|8|9|10] Set the in-home chime duration, in seconds.
>   --help                          Show this message and exit.
>

2024-09-05 07:38 UTC, sdb9696 requested changes
This is a great PR, thanks for the effort!

I would suggest that this would be better implemented as a group of related commands rather than options (also using the `click.BOOL` and `click.IntRange` types as per the comments.  This way the cli would look like:
```
ring-doorbell --device "Front Door" in-home-chime show # Shows all the settings
ring-doorbell --device "Front Door" in-home-chime # Defaults to show the settings
ring-doorbell --device "Front Door" in-home-chime enabled # Shows the enable state
ring-doorbell --device "Front Door" in-home-chime enabled y # Enables/Disables (from the docs: The string values “1”, “true”, “t”, “yes”, “y”, and “on” convert to True. “0”, “false”, “f”, “no”, “n”, and “off” convert to False.)
ring-doorbell --device "Front Door" in-home-chime duration # Shows the duration
ring-doorbell --device "Front Door" in-home-chime duration 5 # Sets the duration
ring-doorbell --device "Front Door" in-home-chime type # Shows the type
ring-doorbell --device "Front Door" in-home-chime duration Mechanical # Sets the type
```
You can set the device on the context in the main group command and `pass_dev` to the sub commands.

2024-09-05 07:38 UTC, sdb9696 commented on ring_doorbell/cli.py
> +)
```suggestion
@click.argument("duration", type=click.IntRange(0, 10), default=None, required=False)
```

2024-09-05 07:38 UTC, sdb9696 commented on ring_doorbell/cli.py
> +)
```suggestion
@click.argument("enable", type=click.BOOL, default=None, required=False)
)
```

2024-09-05 07:38 UTC, sdb9696 commented on ring_doorbell/cli.py
> +)
```suggestion
@click.argument("duration", type=click.Choice(["Mechanical", "Digital", "Not Present"], default=None, required=False)
```

2024-09-05 07:38 UTC, sdb9696 commented on ring_doorbell/cli.py
> +@click.pass_context
```suggestion
@cli.group(invoke_without_command=True)
@pass_ring
@click.pass_context
async def in_home_chime(ctx, dev):
    """Show and modify in home chime settings."""
    if ctx.invoked_subcommand is None:
        return await ctx.invoke(show)
```

2024-09-05 07:46 UTC, sdb9696 commented on ring_doorbell/cli.py
> +    if duration:
```suggestion
@in_home_chime.group()
@pass_dev
@click.pass_context
async def duration(ctx, dev, duration):
    """Show and modify in home chime duration."""
    if duration:
```

2024-09-05 19:55 UTC, sdb9696 commented
Hey just a heads up that I’ve converted the project to use `uv` instead of `poetry`. If you merge with master you’ll need to `pipx install uv` and run things with `uv run` instead of `poetry run` but other that shouldn’t be much impact.

2024-09-08 19:24 UTC, briangoldstein commented
@sdb9696 thank you! My concern with moving them from options to arguments is that it causes the help output to not be as helpful. Great call on moving `duration` to inter. However for `enabled`, I like keeping it locked to a True/False choice type so that it also displays in the help.  

**Help w/ options:**
<img width="513" alt="Screenshot 2024-09-08 at 12 18 32 PM" src="https://github.com/user-attachments/assets/669284b3-cb97-44b7-8447-e3d9845ebca4">

**Help w/ arguments:**
<img width="485" alt="Screenshot 2024-09-08 at 12 16 47 PM" src="https://github.com/user-attachments/assets/e2349b3d-7710-4da8-a63d-d9c90c54ff9c">

2024-09-12 14:17 UTC, sdb9696 commented
> @sdb9696 thank you! My concern with moving them from options to arguments is that it causes the help output to not be as helpful. Great call on moving `duration` to inter. However for `enabled`, I like keeping it locked to a True/False choice type so that it also displays in the help.


Hey @briangoldstein, apologies for the delay in coming back to you.  I've pushed [a commit](https://github.com/python-ring-doorbell/python-ring-doorbell/pull/427/commits/3358d79c1109cf825fd6b0cc0e7e37c2f258026e) to your branch that hopefully explains what I'm trying to achieve.  Essentially I'd like to keep the use of options as light as possible and stick to arguments for the most important part of a command. The help can go in the docstring and I think it looks ok.

Some of the other commands like `motion_detection` aren't currently doing this but they will be moved over eventually.

The downside is you can't set multiple in-home-chime settings in one go but I think that's ok.

There's also some other clean up in there, let me know your thoughts.

2024-09-18 17:28 UTC, sdb9696 commented
Hi @briangoldstein, unless you object and want to revert the commit I added and discuss further, I'll merge this PR in the next day or so.

2024-09-19 07:50 UTC, merged